"""Pydantic schemas, split by domain from the original single-file module.

Import path ``map_types.schemas`` is preserved: every public name is
re-exported here in the original definition order, and the original
trailing ``model_rebuild()`` calls are replayed verbatim, so consumers
(cli / sdk / server / scripts/gen_types.py) are unaffected.
"""

from .project import (
    PROJECT_KEY_PATTERN,
    ProjectCreate,
    ProjectUpdate,
    ProjectRead,
    BootstrapRequest,
    BootstrapAgentResult,
    BootstrapResponse,
    ProjectStatusRead,
    ProjectStatusRevise,
    ProjectStatusVersionRead,
    GlobalStatusRead,
)
from .base import ORMModel
from .plan import (
    PlanInput,
    PlanRevise,
    PlanVersionRead,
)
from .review import (
    ReviewCreate,
    ReviewItemRead,
    ReviewItemUpdate,
    ReviewRead,
)
from .comment import (
    CommentCreate,
    CommentRead,
    CommentTreeNode,
)
from .experiment import (
    ExperimentCreate,
    ExperimentUpdate,
    ExperimentStart,
    ExperimentSummaryRead,
    AcceptanceStatusRead,
    ExperimentDetailRead,
    ExperimentLockRead,
    ExperimentLockStalledScanRead,
    ExperimentLogCreate,
    ExperimentLogRead,
    EvidenceWarningCode,
    EvidenceWarningSchema,
    EvidenceValidationSchema,
    LogCreateResponse,
    TemplateWarningCode,
    TemplateWarningSchema,
    TemplateValidationSchema,
    SimilarityWarningCode,
    SimilarityWarningSchema,
    ExperimentComplete,
    WaivedReason,
    ReviewVerdictItem,
    ReviewInvariantCheck,
    ReviewVerdictFile,
    ExperimentResultDecision,
    ExperimentBundleRead,
)
from .agent import (
    AgentRead,
    AgentCreateResponse,
    AgentCreate,
    EscalationTargetRead,
)
from .topic import (
    TopicCreate,
    TopicUpdate,
    TopicAdvanceRound,
    TopicCloseRequest,
    TopicActionItemCreate,
    ActionItemCancel,
    TopicResolve,
    TopicActionItemRead,
    TopicDecisionRead,
    TopicSummaryRead,
    TopicCommentCreate,
    TopicCommentRead,
    TopicCommentTreeNode,
    TopicRead,
)
from .topic_progress import (
    TopicProgressCommentRead,
    TopicWorkItemRead,
    TopicProgressItemRead,
    TopicProgressListRead,
)
from .todo import (
    PendingReplyRead,
    PendingPlanRevisionRead,
    PendingTopicReplyTodoRead,
    PendingRoundAckTodoRead,
    PendingAdvanceRoundTodoRead,
    StaleOpenTopicTodoRead,
    MentionTodoRead,
    DismissMentionResultRead,
    DismissAllMentionsResultRead,
    TopicReadCursorRead,
    TopicActionItemTodoRead,
    ExperimentReviewInformationalRead,
    TodoRead,
)
from .notification import (
    NotificationRead,
    NotificationListRead,
)
from .agent_work import (
    AgentWorkRead,
    BucketVisibility,
    SummaryBucketKind,
    SummaryBucketItem,
    SummaryBucket,
    AgentWorkSummaryRead,
)
from .inbound_event import (
    InboundEventCreate,
    InboundEventRead,
    InboundEventRecordResult,
)
from .webhook import (
    WebhookCreate,
    WebhookUpdate,
    WebhookRead,
    WebhookCreateResponse,
    WebhookDeliveryRead,
)
from .audit import (
    AuditLogRead,
    CrossPersonaCallRecord,
    ACTION_ITEM_WAKE_SENT,
    ACTION_ITEM_STALE,
    ActionItemWakeSentPayload,
    ActionItemStalePayload,
)
from .feedback import (
    PlatformFeedbackCreate,
    PlatformFeedbackUpdate,
    PlatformFeedbackRead,
)

# Re-export enums: the original single-file module had no ``__all__``, so its
# imported enum names were part of the public surface picked up by
# ``from map_types.schemas import *`` (e.g. the ``server/domain/schemas.py``
# shim). Keep that passthrough intact after the split.
from map_types.enums import (  # noqa: E402
    AcceptanceType,
    ActionItemCategory,
    AgentRole,
    CommentAnchorType,
    ExperimentMode,
    ExperimentPhase,
    FeedbackCategory,
    FeedbackStatus,
    InboundEventSource,
    NotificationCategory,
    NotificationFingerprintVersion,
    PhaseOwner,
    ResolutionReason,
    ReviewArchivedReason,
    ReviewItemKind,
    ReviewItemStatus,
    ReviewSubstituteKind,
    ReviewVerdict,
    TopicActionItemStatus,
    TopicCommentKind,
    TopicDiscussionRound,
    TopicStatus,
)

ProjectStatusRead.model_rebuild()
CommentTreeNode.model_rebuild()
TopicRead.model_rebuild()
TopicCommentTreeNode.model_rebuild()

__all__ = [
    "PROJECT_KEY_PATTERN",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectRead",
    "BootstrapRequest",
    "BootstrapAgentResult",
    "BootstrapResponse",
    "ProjectStatusRead",
    "ProjectStatusRevise",
    "ProjectStatusVersionRead",
    "GlobalStatusRead",
    "ORMModel",
    "PlanInput",
    "PlanRevise",
    "PlanVersionRead",
    "ReviewCreate",
    "ReviewItemRead",
    "ReviewItemUpdate",
    "ReviewRead",
    "CommentCreate",
    "CommentRead",
    "CommentTreeNode",
    "ExperimentCreate",
    "ExperimentUpdate",
    "ExperimentStart",
    "ExperimentSummaryRead",
    "AcceptanceStatusRead",
    "ExperimentDetailRead",
    "ExperimentLockRead",
    "ExperimentLockStalledScanRead",
    "ExperimentLogCreate",
    "ExperimentLogRead",
    "EvidenceWarningCode",
    "EvidenceWarningSchema",
    "EvidenceValidationSchema",
    "LogCreateResponse",
    "TemplateWarningCode",
    "TemplateWarningSchema",
    "TemplateValidationSchema",
    "SimilarityWarningCode",
    "SimilarityWarningSchema",
    "ExperimentComplete",
    "WaivedReason",
    "ReviewVerdictItem",
    "ReviewInvariantCheck",
    "ReviewVerdictFile",
    "ExperimentResultDecision",
    "ExperimentBundleRead",
    "AgentRead",
    "AgentCreateResponse",
    "AgentCreate",
    "EscalationTargetRead",
    "TopicCreate",
    "TopicUpdate",
    "TopicAdvanceRound",
    "TopicCloseRequest",
    "TopicActionItemCreate",
    "ActionItemCancel",
    "TopicResolve",
    "TopicActionItemRead",
    "TopicDecisionRead",
    "TopicSummaryRead",
    "TopicCommentCreate",
    "TopicCommentRead",
    "TopicCommentTreeNode",
    "TopicRead",
    "TopicProgressCommentRead",
    "TopicWorkItemRead",
    "TopicProgressItemRead",
    "TopicProgressListRead",
    "PendingReplyRead",
    "PendingPlanRevisionRead",
    "PendingTopicReplyTodoRead",
    "PendingRoundAckTodoRead",
    "PendingAdvanceRoundTodoRead",
    "StaleOpenTopicTodoRead",
    "MentionTodoRead",
    "DismissMentionResultRead",
    "DismissAllMentionsResultRead",
    "TopicReadCursorRead",
    "TopicActionItemTodoRead",
    "ExperimentReviewInformationalRead",
    "TodoRead",
    "NotificationRead",
    "NotificationListRead",
    "AgentWorkRead",
    "BucketVisibility",
    "SummaryBucketKind",
    "SummaryBucketItem",
    "SummaryBucket",
    "AgentWorkSummaryRead",
    "InboundEventCreate",
    "InboundEventRead",
    "InboundEventRecordResult",
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookRead",
    "WebhookCreateResponse",
    "WebhookDeliveryRead",
    "AuditLogRead",
    "CrossPersonaCallRecord",
    "ACTION_ITEM_WAKE_SENT",
    "ACTION_ITEM_STALE",
    "ActionItemWakeSentPayload",
    "ActionItemStalePayload",
    "PlatformFeedbackCreate",
    "PlatformFeedbackUpdate",
    "PlatformFeedbackRead",
    "AcceptanceType",
    "ActionItemCategory",
    "AgentRole",
    "CommentAnchorType",
    "ExperimentMode",
    "ExperimentPhase",
    "FeedbackCategory",
    "FeedbackStatus",
    "InboundEventSource",
    "NotificationCategory",
    "NotificationFingerprintVersion",
    "PhaseOwner",
    "ResolutionReason",
    "ReviewArchivedReason",
    "ReviewItemKind",
    "ReviewItemStatus",
    "ReviewSubstituteKind",
    "ReviewVerdict",
    "TopicActionItemStatus",
    "TopicCommentKind",
    "TopicDiscussionRound",
    "TopicStatus",
]
