"""Export project history (topics, experiments, decisions) to local Markdown.

This is "Plan B" of the data-portability roadmap: a read-only snapshot
that lives under ``.map/history/`` by default (local runtime, gitignored).
Pass ``-o`` to a tracked path such as ``docs/history`` if the snapshot
should travel with the code via Git.

Usage (called from ``cli/commands/project.py``)::

    from cli.project_export import export_project_history
    export_project_history(client, project_id, output_dir, include_archived=...)
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from pathlib import Path

from map_client.client import MAPClient
from map_types.schemas import (
    ExperimentBundleRead,
    TopicCommentTreeNode,
    TopicDecisionRead,
    TopicRead,
)

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def export_project_history(
    client: MAPClient,
    project_id: uuid.UUID,
    output_dir: Path,
    *,
    include_archived: bool = True,
) -> Path:
    """Export all project topics + experiments to ``output_dir`` as Markdown.

    Layout::

        output_dir/
          INDEX.md              ← 可浏览的总目录
          topics/
            <slug>.md           ← 每个话题一篇（含评论树 + 决策 + 行动项）
          experiments/
            <slug>.md           ← 每个实验一篇（含计划 + 评审 + 日志）

    Returns the ``output_dir`` path.
    """
    topics_dir = output_dir / "topics"
    experiments_dir = output_dir / "experiments"
    topics_dir.mkdir(parents=True, exist_ok=True)
    experiments_dir.mkdir(parents=True, exist_ok=True)

    # Fetch all topics (paginated)
    all_topics: list[TopicRead] = []
    page = 1
    while True:
        batch = client.list_topics(
            project_id,
            page=page,
            page_size=100,
            include_archived=include_archived,
        )
        if not batch:
            break
        for summary in batch:
            topic = client.get_topic(summary.id)
            all_topics.append(topic)
        if len(batch) < 100:
            break
        page += 1

    # Fetch all experiments (paginated)
    all_experiment_bundles: list[ExperimentBundleRead] = []
    page = 1
    while True:
        batch = client.list_experiments(
            project_id,
            page=page,
            page_size=100,
            include_archived=include_archived,
        )
        if not batch:
            break
        for summary in batch:
            bundle = client.get_experiment_bundle(summary.id)
            all_experiment_bundles.append(bundle)
        if len(batch) < 100:
            break
        page += 1

    # Write topic files
    topic_entries: list[dict[str, str]] = []
    for topic in all_topics:
        slug = _slugify(topic.title)
        fname = f"{slug}.md"
        content = _render_topic(topic)
        (topics_dir / fname).write_text(content, encoding="utf-8")
        topic_entries.append({
            "title": topic.title,
            "status": topic.status.value if hasattr(topic.status, "value") else str(topic.status),
            "file": f"topics/{fname}",
            "decision": "yes" if topic.decision else "no",
        })

    # Write experiment files
    experiment_entries: list[dict[str, str]] = []
    for bundle in all_experiment_bundles:
        exp = bundle.experiment
        slug = _slugify(exp.title)
        fname = f"{slug}.md"
        content = _render_experiment(bundle)
        (experiments_dir / fname).write_text(content, encoding="utf-8")
        experiment_entries.append({
            "title": exp.title,
            "phase": exp.phase.value if hasattr(exp.phase, "value") else str(exp.phase),
            "file": f"experiments/{fname}",
        })

    # Write index
    index_content = _render_index(topic_entries, experiment_entries)
    (output_dir / "INDEX.md").write_text(index_content, encoding="utf-8")

    return output_dir


# ---------------------------------------------------------------------------
# Markdown renderers
# ---------------------------------------------------------------------------


def _render_index(
    topics: list[dict[str, str]],
    experiments: list[dict[str, str]],
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Project History Export",
        "",
        f"> Exported at {now}. This is a read-only snapshot from the MAP server.",
        "> Generated by `map project export`.",
        "",
        f"## Topics ({len(topics)})",
        "",
        "| Title | Status | Decision | File |",
        "|-------|--------|----------|------|",
    ]
    for t in topics:
        lines.append(f"| {t['title']} | {t['status']} | {t['decision']} | [{t['file']}]({t['file']}) |")
    lines.extend([
        "",
        f"## Experiments ({len(experiments)})",
        "",
        "| Title | Phase | File |",
        "|-------|-------|------|",
    ])
    for e in experiments:
        lines.append(f"| {e['title']} | {e['phase']} | [{e['file']}]({e['file']}) |")
    lines.append("")
    return "\n".join(lines)


def _render_topic(topic: TopicRead) -> str:
    lines: list[str] = [
        f"# {topic.title}",
        "",
        f"- **Topic ID**: `{topic.id}`",
        f"- **Status**: {topic.status.value if hasattr(topic.status, 'value') else topic.status}",
        f"- **Discussion Round**: {topic.discussion_round}",
        f"- **Creator**: {topic.creator_name or topic.creator_agent_id}",
        f"- **Created At**: {_fmt_dt(getattr(topic, 'created_at', None))}",
    ]
    if topic.description:
        lines.extend(["", "## Description", "", topic.description])

    # Comments tree
    if topic.comments:
        lines.extend(["", "## Discussion", ""])
        for node in topic.comments:
            lines.extend(_render_comment_node(node, depth=0))

    # Decision
    if topic.decision:
        lines.extend(["", "## Decision", ""])
        lines.extend(_render_decision(topic.decision))

    # Linked experiments
    if topic.experiments:
        lines.extend(["", "## Linked Experiments", ""])
        for exp in topic.experiments:
            phase = exp.phase.value if hasattr(exp.phase, "value") else exp.phase
            lines.append(f"- **{exp.title}** ({phase}) — `{exp.id}`")

    lines.append("")
    return "\n".join(lines)


def _render_comment_node(node: TopicCommentTreeNode, depth: int) -> list[str]:
    indent = "  " * depth
    author = node.author_name or str(node.author_agent_id)
    created = _fmt_dt(node.created_at)
    kind_tag = ""
    if hasattr(node, "kind") and node.kind and str(node.kind) != "user":
        kind_tag = f" [{node.kind}]"
    lines = [
        f"{indent}### {author}{kind_tag} — {created}",
        "",
        f"{indent}> _Comment ID: `{node.id}`_",
        "",
    ]
    # Indent body
    for body_line in node.body.splitlines():
        lines.append(f"{indent}{body_line}")
    lines.append("")
    for child in node.children:
        lines.extend(_render_comment_node(child, depth + 1))
    return lines


def _render_decision(decision: TopicDecisionRead) -> list[str]:
    lines: list[str] = []
    if decision.decision:
        lines.extend([f"**Decision**: {decision.decision}", ""])
    if decision.rationale:
        lines.extend(["**Rationale**:", "", decision.rationale, ""])
    if decision.rejected_options:
        lines.extend(["**Rejected Options**:", "", decision.rejected_options, ""])
    if decision.open_questions:
        lines.extend(["**Open Questions**:", "", decision.open_questions, ""])
    if decision.no_decision_reason:
        lines.extend([f"**No Decision**: {decision.no_decision_reason}", ""])
    if decision.action_items:
        lines.extend(["### Action Items", "", "| Title | Status | Owner | Due |", "|-------|--------|-------|-----|"])
        for item in decision.action_items:
            owner = item.owner_name or "—"
            due = _fmt_dt(item.due_at) if item.due_at else "—"
            status = item.status.value if hasattr(item.status, "value") else str(item.status)
            lines.append(f"| {item.title} | {status} | {owner} | {due} |")
        lines.append("")
    if not lines:
        lines.append("_No decision recorded._")
    return lines


def _render_experiment(bundle: ExperimentBundleRead) -> str:
    exp = bundle.experiment
    lines: list[str] = [
        f"# {exp.title}",
        "",
        f"- **Experiment ID**: `{exp.id}`",
        f"- **Phase**: {exp.phase.value if hasattr(exp.phase, 'value') else exp.phase}",
        f"- **Creator**: {exp.creator_agent_id}",
        f"- **Current Plan Version**: {exp.current_plan_version}",
        f"- **Created At**: {_fmt_dt(exp.created_at)}",
        f"- **Updated At**: {_fmt_dt(exp.updated_at)}",
    ]
    if exp.topic_id:
        lines.append(f"- **Linked Topic**: `{exp.topic_id}`")
    if exp.description:
        lines.extend(["", "## Description", "", exp.description])

    # Plans
    if bundle.plans:
        lines.extend(["", "## Plan Versions", ""])
        for plan in bundle.plans:
            lines.extend([
                f"### Version {plan.version}",
                "",
                f"- **Author**: {plan.author_agent_id}",
                f"- **Created At**: {_fmt_dt(plan.created_at)}",
                "",
                plan.content_md,
                "",
            ])

    # Reviews
    if bundle.reviews:
        lines.extend(["", "## Reviews", ""])
        for review in bundle.reviews:
            reviewer = review.reviewer_agent_id
            lines.extend([
                f"### Review by {reviewer}",
                "",
                f"- **Status**: {review.status}",
                f"- **Created At**: {_fmt_dt(review.created_at)}",
                "",
            ])
            if review.summary:
                lines.extend([review.summary, ""])
            if review.items:
                lines.extend(["| # | Description | Type | Status |", "|---|-------------|------|--------|"])
                for i, item in enumerate(review.items, 1):
                    item_status = item.status.value if hasattr(item.status, "value") else str(item.status)
                    item_type = item.acceptance_type or "—"
                    lines.append(f"| {i} | {item.description} | {item_type} | {item_status} |")
                lines.append("")

    # Comments
    if bundle.comments:
        lines.extend(["", "## Comments", ""])
        for node in bundle.comments:
            lines.extend(_render_comment_node(node, depth=0))

    # Logs
    if bundle.logs:
        lines.extend(["", "## Experiment Logs", ""])
        for log in bundle.logs:
            lines.extend([
                f"### Log Entry — {_fmt_dt(log.created_at)}",
                "",
                f"- **Author**: {log.author_agent_id}",
                "",
                log.content_md if hasattr(log, "content_md") else str(log.content),
                "",
            ])

    # Acceptance status
    if exp.acceptance_status:
        lines.extend(["", "## Acceptance Status", "", "| # | Description | Type | Evidence | Verdict |", "|---|-------------|------|----------|---------|"])
        for i, acc in enumerate(exp.acceptance_status, 1):
            evidence = "yes" if acc.evidence_provided else "no"
            verdict = acc.reviewer_verdict or "—"
            lines.append(f"| {i} | {acc.description} | {acc.acceptance_type} | {evidence} | {verdict} |")
        lines.append("")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _slugify(text: str) -> str:
    """Create a filesystem-safe slug from a title."""
    import re
    # Replace non-alphanumeric with hyphens, collapse, strip, lowercase
    slug = re.sub(r"[^\w\s-]", "", text).strip().lower()
    slug = re.sub(r"[-\s]+", "-", slug)
    # Truncate to reasonable length
    return slug[:80] or "untitled"


def _fmt_dt(dt: datetime | None) -> str:
    if dt is None:
        return "—"
    if hasattr(dt, "strftime"):
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    return str(dt)
