"""``map feedback`` — GitHub issue 引导命令 + v0.15 M62 退役 stub。

主命令（裸 ``map feedback``，离线、不连 API）：收集环境信息
（map / Python / OS / api_url），生成预填好的 GitHub issue 链接
（bug / idea 两种模板），打印 URL 供 Agent 转交人类；``--open``
可直接拉起浏览器。repo 默认为上游 ``quantaeye/multi-agent-platform``，
``--repo`` 覆盖（私有 fork 场景）。

旧平台死信箱四命令（submit/list/get/update）保留 exit 2 引导性拒绝
（M58 ``_DB_WRITE_RETIRED`` 同款模式；全链路废弃定案见话题
v015-feedback-deprecation-design round2）。历史数据只读保留于平台 DB，
人类友好索引 = 实验 m62-feedback-deprecation 清账处置表。
"""

from __future__ import annotations

import platform as _platform
import urllib.parse
import webbrowser
from enum import Enum

import typer

feedback_app = typer.Typer(help="Open a prefilled GitHub issue (bug / idea); legacy inbox subcommands are retired")

DEFAULT_FEEDBACK_REPO = "quantaeye/multi-agent-platform"

_HINT = (
    "Platform feedback inbox was retired in v0.15 M62 (dead-letter box: no recipient on "
    "self-hosted deployments).\n"
    "- bug / tool improvement: run `map feedback` to open a prefilled GitHub issue\n"
    "- dogfood feedback (inside a MAP project): ask the host to open a MAP topic\n"
    "Historical feedback records are preserved read-only in the platform DB."
)


class FeedbackKind(str, Enum):
    BUG = "bug"
    IDEA = "idea"


def _env_lines() -> list[str]:
    from cli.main import _cli_options, _cli_version  # runtime state (monkeypatch surface)

    lines = [
        f"- map version: {_cli_version()}",
        f"- Python: {_platform.python_version()}",
        f"- OS: {_platform.platform()}",
    ]
    lines.append(f"- MAP server: {_detect_api_url(_cli_options.get('project_root'))}")
    return lines


def _detect_api_url(project_root) -> str:
    try:
        import yaml
        from map_client.project_config import find_map_dir

        map_dir = find_map_dir(project_root)
        if map_dir is None:
            return "(no .map/config.yaml found)"
        config = yaml.safe_load((map_dir / "config.yaml").read_text(encoding="utf-8")) or {}
        return str(config.get("api_url") or "(api_url not set)")
    except Exception:
        return "(unknown)"


@feedback_app.callback(invoke_without_command=True)
def feedback_main(
    ctx: typer.Context,
    kind: FeedbackKind = typer.Option(
        FeedbackKind.BUG, "--type", help="Issue template: bug report or improvement idea"
    ),
    title: str | None = typer.Option(None, "--title", help="Issue title (auto-prefixed with [bug]/[idea])"),
    body: str | None = typer.Option(
        None, "--body", help="Issue description (can also be filled in the GitHub editor)"
    ),
    repo: str = typer.Option(
        DEFAULT_FEEDBACK_REPO, "--repo", help="GitHub repo in owner/name form (for private forks)"
    ),
    open_browser: bool = typer.Option(False, "--open", help="Launch the browser at the generated URL"),
) -> None:
    """Generate a prefilled GitHub issue link with environment info attached."""
    if ctx.invoked_subcommand is not None:
        return

    issue_title = f"[{kind.value}] {title}" if title else f"[{kind.value}] <short title>"
    env = _env_lines()
    if kind is FeedbackKind.BUG:
        sections = ("## Problem", body or "<describe the problem, including steps to reproduce>")
    else:
        sections = ("## Proposal", body or "<describe your idea>")
    issue_body = "\n".join(
        [
            sections[0],
            "",
            sections[1],
            "",
            "## Environment" if kind is FeedbackKind.BUG else "## Context",
            "",
            *env,
            "",
            "<!-- Environment block generated by `map feedback` -->",
        ]
    )
    url = (
        f"https://github.com/{repo}/issues/new?"
        + urllib.parse.urlencode({"title": issue_title, "body": issue_body})
    )

    typer.echo(url)
    typer.echo("")
    typer.echo(f"Prefilled {kind.value} issue for {repo} (map version, Python and OS attached).")
    if open_browser:
        webbrowser.open(url)
        typer.echo("Opened in your browser.")
    else:
        typer.echo("Open the URL above in a browser to finish filing (add --open to launch it directly).")


def _feedback_retired(command: str) -> None:
    typer.echo(f"Error: `map feedback {command}` is retired (v0.15 M62).\n{_HINT}", err=True)
    raise typer.Exit(2)


@feedback_app.command("submit")
def feedback_submit(
    body: str | None = typer.Option(None, "--body", help="Retained for shell compat; command always exits 2."),
    body_file: str | None = typer.Option(None, "--file", help="Retained for shell compat; command always exits 2."),
) -> None:
    _feedback_retired("submit")


@feedback_app.command("list")
def feedback_list(
    status: str | None = typer.Option(None, "--status"),
    category: str | None = typer.Option(None, "--category"),
    project: str | None = typer.Option(None, "--project"),
    page: int = typer.Option(1, "--page", min=1),
    page_size: int = typer.Option(50, "--page-size", min=1, max=200),
    include_archived: bool = typer.Option(False, "--include-archived"),
) -> None:
    _feedback_retired("list")


@feedback_app.command("get")
def feedback_get(feedback_id: str = typer.Argument(..., help="Retained for shell compat; command always exits 2.")) -> None:
    _feedback_retired("get")


@feedback_app.command("update")
def feedback_update(
    feedback_id: str = typer.Argument(..., help="Retained for shell compat; command always exits 2."),
    status: str | None = typer.Option(None, "--status"),
    category: str | None = typer.Option(None, "--category"),
    archived: bool | None = typer.Option(None, "--archived/--no-archived"),
) -> None:
    _feedback_retired("update")
